# Generated by Django 3.1.2 on 2020-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20201207_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
