# Generated by Django 3.1.3 on 2020-12-08 14:20

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20201207_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(default='187 kb', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=storage.models.get_upload_path),
        ),
    ]
