# Generated by Django 3.1.3 on 2020-12-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_file_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user_id',
            new_name='user',
        ),
    ]
