# Generated by Django 3.1.3 on 2020-12-21 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20201208_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
